/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pritt;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author theo1038
 */
public class MainFrame extends javax.swing.JFrame {
    
    private File source,destination;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        try {
            Image i = ImageIO.read(getClass().getResource("/pritt/icon.png"));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        collationField = new javax.swing.JTextField();
        outputField = new javax.swing.JTextField();
        collationButton = new javax.swing.JButton();
        outputButton = new javax.swing.JButton();
        transcriptionButton = new javax.swing.JButton();
        matrixButton = new javax.swing.JButton();
        createRoelliButton = new javax.swing.JButton();
        createBarbaraButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pritt");

        collationField.setToolTipText("");
        collationField.setName("collationFileField"); // NOI18N

        outputField.setName("traditionFileField"); // NOI18N

        collationButton.setText("Collation");
        collationButton.setName("collationButton"); // NOI18N
        collationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collationButtonActionPerformed(evt);
            }
        });

        outputButton.setLabel("Output");
        outputButton.setName("outputButton"); // NOI18N
        outputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputButtonActionPerformed(evt);
            }
        });

        transcriptionButton.setText("Create Transcription");
        transcriptionButton.setActionCommand("");
        transcriptionButton.setName("transcriptionButton"); // NOI18N
        transcriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcriptionButtonActionPerformed(evt);
            }
        });

        matrixButton.setText("Create Matrix");
        matrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixButtonActionPerformed(evt);
            }
        });

        createRoelliButton.setText("Create Roelli");
        createRoelliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoelliButtonActionPerformed(evt);
            }
        });

        createBarbaraButton.setText("Create Barbara");
        createBarbaraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBarbaraButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(collationField)
                            .add(outputField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(collationButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(outputButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, createRoelliButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, transcriptionButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(matrixButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(createBarbaraButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(collationField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(collationButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(outputField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(outputButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(transcriptionButton)
                    .add(matrixButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(createRoelliButton)
                    .add(createBarbaraButton)))
        );

        createRoelliButton.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputButtonActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        f.setDialogTitle("Select the destination file or directory for the output");
        int retval = f.showSaveDialog(this);
        if(retval == JFileChooser.APPROVE_OPTION)
        {
            outputField.setText(f.getSelectedFile().getAbsolutePath());
            destination = f.getSelectedFile();
        }
    }//GEN-LAST:event_outputButtonActionPerformed

    private void collationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collationButtonActionPerformed
        JFileChooser f = new JFileChooser();
        f.setDialogTitle("Select the source file or directory with the collation(s)");
        f.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int retval = f.showOpenDialog(this);
        if(retval == JFileChooser.APPROVE_OPTION)
        {
            collationField.setText(f.getSelectedFile().getAbsolutePath());
            source = f.getSelectedFile();
        }
    }//GEN-LAST:event_collationButtonActionPerformed

    private void transcriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcriptionButtonActionPerformed
        if(source != null && destination != null)
        {
            Pritt p = new Pritt();
            p.createTranscription(source, destination);
        }
    }//GEN-LAST:event_transcriptionButtonActionPerformed

    private void matrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixButtonActionPerformed
        if(source != null && destination != null)
        {
            Pritt p = new Pritt();
            p.createMatrix(source, destination);
        }
    }//GEN-LAST:event_matrixButtonActionPerformed

    private void createRoelliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoelliButtonActionPerformed
    if(source != null && destination != null)
        {
            Pritt p = new Pritt();
            p.createRoelli(source, destination);
        }
    }//GEN-LAST:event_createRoelliButtonActionPerformed

    private void createBarbaraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBarbaraButtonActionPerformed
     if(source != null && destination != null)
        {
            Pritt p = new Pritt();
            p.createBarbara(source, destination);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_createBarbaraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton collationButton;
    private javax.swing.JTextField collationField;
    private javax.swing.JButton createBarbaraButton;
    private javax.swing.JButton createRoelliButton;
    private javax.swing.JButton matrixButton;
    private javax.swing.JButton outputButton;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton transcriptionButton;
    // End of variables declaration//GEN-END:variables
}
